### ISSUE TITLE
Persistance de l'erreur de  mémoire insuffisante

### ISSUE THREAD

**Issue by kbeauvivre** [vibby/likertSurvey#5]
![image](https://user-images.githubusercontent.com/37898272/38089392-91df2484-335f-11e8-8f39-fcfcd64fa5d1.png)

**Comment by kbeauvivre** [comment]
J'ai testé d'indiquer uniquement mon adresse email et cocher la première case.
Voici l'erreur que j'obtiens :
![image](https://user-images.githubusercontent.com/37898272/38091880-0be941fe-3367-11e8-86f2-f9569dac8253.png)

La même erreur apparaît lorsque j'indique les adresses d'un collaborateur, puis d'un collaborateur et d'un manager.
Ce n'est que lorsque j'indique une adresse de collègue que l'erreur de mémoire insuffisante apparaît.

C'est difficile d'identifier exactement les conditions dans lesquelles l'erreur mangue de mémoire a lieu. En remettant des adresses email dans chaque champ plus des adresses supplémentaires dans ure des catégories, c'est plutôt l'erreur 500 qui survient.

**Comment by vibby** [comment]
Problème identifié mais pas encore de solution : on boucle sur l’assignation d’un collaborateur, auquel on assigne le manager, auquel on assigne le collaborateur, auquel on assigne le manager, auquel on assigne le collaborateur, auquel on assigne le manager, auquel on assigne le collaborateur, auquel on assigne le manager, auquel on assigne le collaborateur… bref.

**Comment by kbeauvivre** [comment]
Est-ce que tu peux faire un truc du genre :
Lorsque A indique l'adresse email de son collaborateur B, tu recherches dans la base si cette adresse a donné lieu à une clé d'activation. Si non, tu la crées, si oui, tu regardes si le champ "manager" est renseigné. Si non, tu écris la clé d'activation de A, si oui, tu ne touches à rien.
Idem pour les autres catégories (manager et collègues).
J'espère ne pas raconter trop de bêtises en disant ça ...
